/**
 * ICD-10-CM 代碼資料庫
 * 家醫科常用代碼中文對照
 *
 * 資料結構：
 *   code: ICD-10-CM 代碼
 *   zh:   中文名稱
 *   en:   英文名稱
 *   cat:  分類
 *   kw:   (選填) 額外搜尋關鍵字，例如別名、簡稱
 *
 * 擴充方式：直接在陣列中新增資料，網站會自動索引
 */

const ICD_DATA = [
  // ========== 糖尿病 ==========
  { code: "E11.9",   zh: "第2型糖尿病，無併發症",          en: "Type 2 diabetes mellitus without complications", cat: "糖尿病", kw: "T2DM DM2" },
  { code: "E11.65",  zh: "第2型糖尿病伴高血糖",            en: "Type 2 DM with hyperglycemia", cat: "糖尿病", kw: "T2DM" },
  { code: "E11.22",  zh: "第2型糖尿病伴糖尿病腎病變",       en: "Type 2 DM with diabetic chronic kidney disease", cat: "糖尿病", kw: "DKD" },
  { code: "E11.21",  zh: "第2型糖尿病伴糖尿病腎病",         en: "Type 2 DM with diabetic nephropathy", cat: "糖尿病" },
  { code: "E11.40",  zh: "第2型糖尿病伴糖尿病神經病變，未特定", en: "Type 2 DM with diabetic neuropathy, unspecified", cat: "糖尿病" },
  { code: "E11.42",  zh: "第2型糖尿病伴糖尿病多發性神經病變", en: "Type 2 DM with diabetic polyneuropathy", cat: "糖尿病" },
  { code: "E11.319", zh: "第2型糖尿病伴無黃斑水腫之視網膜病變", en: "Type 2 DM with unspecified diabetic retinopathy without macular edema", cat: "糖尿病" },
  { code: "E11.311", zh: "第2型糖尿病伴有黃斑水腫之視網膜病變", en: "Type 2 DM with unspecified diabetic retinopathy with macular edema", cat: "糖尿病" },
  { code: "E11.51",  zh: "第2型糖尿病伴周邊血管病變，無壞疽", en: "Type 2 DM with diabetic peripheral angiopathy without gangrene", cat: "糖尿病" },
  { code: "E11.52",  zh: "第2型糖尿病伴周邊血管病變伴壞疽", en: "Type 2 DM with diabetic peripheral angiopathy with gangrene", cat: "糖尿病" },
  { code: "E11.621", zh: "第2型糖尿病伴糖尿病足潰瘍",       en: "Type 2 DM with foot ulcer", cat: "糖尿病" },
  { code: "E11.8",   zh: "第2型糖尿病伴未特定併發症",       en: "Type 2 DM with unspecified complications", cat: "糖尿病" },
  { code: "E10.9",   zh: "第1型糖尿病，無併發症",          en: "Type 1 diabetes mellitus without complications", cat: "糖尿病", kw: "T1DM" },
  { code: "E10.65",  zh: "第1型糖尿病伴高血糖",            en: "Type 1 DM with hyperglycemia", cat: "糖尿病" },
  { code: "E13.9",   zh: "其他特定糖尿病，無併發症",        en: "Other specified DM without complications", cat: "糖尿病" },
  { code: "E08.9",   zh: "續發於潛在疾病之糖尿病，無併發症", en: "DM due to underlying condition without complications", cat: "糖尿病" },
  { code: "O24.410", zh: "妊娠糖尿病，飲食控制",            en: "Gestational diabetes mellitus in pregnancy, diet controlled", cat: "糖尿病", kw: "GDM" },
  { code: "O24.414", zh: "妊娠糖尿病，胰島素控制",          en: "Gestational diabetes mellitus in pregnancy, insulin controlled", cat: "糖尿病", kw: "GDM" },
  { code: "R73.03",  zh: "糖尿病前期",                   en: "Prediabetes", cat: "糖尿病" },
  { code: "R73.09",  zh: "其他異常葡萄糖",                en: "Other abnormal glucose", cat: "糖尿病" },
  { code: "Z79.4",   zh: "長期使用胰島素",                en: "Long term (current) use of insulin", cat: "糖尿病" },
  { code: "Z79.84",  zh: "長期使用口服降血糖藥",           en: "Long term use of oral hypoglycemic drugs", cat: "糖尿病" },
  { code: "E16.2",   zh: "低血糖，未特定",                en: "Hypoglycemia, unspecified", cat: "糖尿病" },

  // ========== 高血壓 ==========
  { code: "I10",     zh: "原發性（本態性）高血壓",          en: "Essential (primary) hypertension", cat: "高血壓", kw: "HTN" },
  { code: "I11.9",   zh: "高血壓性心臟病，無心衰竭",         en: "Hypertensive heart disease without heart failure", cat: "高血壓" },
  { code: "I11.0",   zh: "高血壓性心臟病，伴心衰竭",         en: "Hypertensive heart disease with heart failure", cat: "高血壓" },
  { code: "I12.9",   zh: "高血壓性慢性腎病，第1-4期或未特定", en: "Hypertensive CKD with stage 1-4 or unspecified CKD", cat: "高血壓" },
  { code: "I12.0",   zh: "高血壓性慢性腎病，第5期或ESRD",    en: "Hypertensive CKD with stage 5 CKD or ESRD", cat: "高血壓" },
  { code: "I13.10",  zh: "高血壓性心腎疾病，無心衰竭",        en: "Hypertensive heart and CKD without heart failure", cat: "高血壓" },
  { code: "I13.0",   zh: "高血壓性心腎疾病，伴心衰竭",        en: "Hypertensive heart and CKD with heart failure", cat: "高血壓" },
  { code: "I15.9",   zh: "續發性高血壓，未特定",             en: "Secondary hypertension, unspecified", cat: "高血壓" },
  { code: "I15.0",   zh: "腎血管性高血壓",                 en: "Renovascular hypertension", cat: "高血壓" },
  { code: "I16.9",   zh: "高血壓危象，未特定",              en: "Hypertensive crisis, unspecified", cat: "高血壓" },
  { code: "O13.9",   zh: "妊娠高血壓，未特定",              en: "Gestational hypertension, unspecified", cat: "高血壓" },
  { code: "R03.0",   zh: "收縮壓升高讀數，無高血壓診斷",       en: "Elevated BP reading, without diagnosis of hypertension", cat: "高血壓" },

  // ========== 高血脂 ==========
  { code: "E78.5",   zh: "血脂異常，未特定",               en: "Hyperlipidemia, unspecified", cat: "高血脂" },
  { code: "E78.00",  zh: "純高膽固醇血症，未特定",          en: "Pure hypercholesterolemia, unspecified", cat: "高血脂" },
  { code: "E78.01",  zh: "家族性高膽固醇血症",              en: "Familial hypercholesterolemia", cat: "高血脂" },
  { code: "E78.1",   zh: "純高三酸甘油酯血症",             en: "Pure hyperglyceridemia", cat: "高血脂" },
  { code: "E78.2",   zh: "混合型高血脂症",                en: "Mixed hyperlipidemia", cat: "高血脂" },
  { code: "E78.3",   zh: "高乳糜微粒血症",                en: "Hyperchylomicronemia", cat: "高血脂" },
  { code: "E78.4",   zh: "其他高血脂症",                  en: "Other hyperlipidemia", cat: "高血脂" },
  { code: "E78.6",   zh: "脂蛋白缺乏",                   en: "Lipoprotein deficiency", cat: "高血脂" },
  { code: "E78.70",  zh: "膽汁酸及膽固醇代謝異常，未特定",    en: "Disorder of bile acid and cholesterol metabolism, unspecified", cat: "高血脂" },
  { code: "E88.81",  zh: "代謝症候群",                    en: "Metabolic syndrome", cat: "高血脂" },

  // ========== 心血管 ==========
  { code: "I25.10",  zh: "動脈粥樣硬化性心臟病（原生冠狀動脈），無心絞痛", en: "Atherosclerotic heart disease of native coronary artery without angina", cat: "心血管", kw: "CAD ASHD" },
  { code: "I25.110", zh: "動脈粥樣硬化性心臟病，伴不穩定型心絞痛", en: "ASHD with unstable angina", cat: "心血管" },
  { code: "I25.119", zh: "動脈粥樣硬化性心臟病，伴未特定心絞痛", en: "ASHD with unspecified angina", cat: "心血管" },
  { code: "I25.2",   zh: "陳舊性心肌梗塞",                 en: "Old myocardial infarction", cat: "心血管" },
  { code: "I25.9",   zh: "慢性缺血性心臟病，未特定",         en: "Chronic ischemic heart disease, unspecified", cat: "心血管" },
  { code: "I21.4",   zh: "急性非 ST 段升高心肌梗塞",         en: "Non-ST elevation myocardial infarction", cat: "心血管", kw: "NSTEMI" },
  { code: "I21.3",   zh: "急性 ST 段升高心肌梗塞，未特定部位", en: "ST elevation MI of unspecified site", cat: "心血管", kw: "STEMI" },
  { code: "I20.9",   zh: "心絞痛，未特定",                 en: "Angina pectoris, unspecified", cat: "心血管" },
  { code: "I20.0",   zh: "不穩定型心絞痛",                 en: "Unstable angina", cat: "心血管" },
  { code: "I48.91",  zh: "心房顫動，未特定",               en: "Atrial fibrillation, unspecified", cat: "心血管", kw: "Afib AF" },
  { code: "I48.0",   zh: "陣發性心房顫動",                en: "Paroxysmal atrial fibrillation", cat: "心血管" },
  { code: "I48.1",   zh: "持續性心房顫動",                en: "Persistent atrial fibrillation", cat: "心血管" },
  { code: "I48.2",   zh: "慢性心房顫動",                  en: "Chronic atrial fibrillation", cat: "心血管" },
  { code: "I49.9",   zh: "心律不整，未特定",               en: "Cardiac arrhythmia, unspecified", cat: "心血管" },
  { code: "I49.8",   zh: "其他特定心律不整",               en: "Other specified cardiac arrhythmias", cat: "心血管" },
  { code: "I47.1",   zh: "陣發性室上性心搏過速",            en: "Supraventricular tachycardia", cat: "心血管", kw: "SVT" },
  { code: "R00.0",   zh: "心搏過速，未特定",               en: "Tachycardia, unspecified", cat: "心血管" },
  { code: "R00.1",   zh: "心搏過緩，未特定",               en: "Bradycardia, unspecified", cat: "心血管" },
  { code: "R00.2",   zh: "心悸",                        en: "Palpitations", cat: "心血管" },
  { code: "I50.9",   zh: "心衰竭，未特定",                en: "Heart failure, unspecified", cat: "心血管", kw: "CHF" },
  { code: "I50.22",  zh: "慢性收縮性（鬱血性）心衰竭",       en: "Chronic systolic (congestive) heart failure", cat: "心血管", kw: "HFrEF" },
  { code: "I50.32",  zh: "慢性舒張性（鬱血性）心衰竭",       en: "Chronic diastolic (congestive) heart failure", cat: "心血管", kw: "HFpEF" },
  { code: "I50.42",  zh: "慢性混合型收縮與舒張性心衰竭",      en: "Chronic combined systolic and diastolic heart failure", cat: "心血管" },
  { code: "I50.1",   zh: "左心衰竭",                     en: "Left ventricular failure", cat: "心血管" },
  { code: "I63.9",   zh: "腦梗塞，未特定",                en: "Cerebral infarction, unspecified", cat: "心血管", kw: "stroke CVA" },
  { code: "I69.30",  zh: "腦梗塞後遺症，無特定併發症",       en: "Unspecified sequelae of cerebral infarction", cat: "心血管" },
  { code: "I65.9",   zh: "大腦動脈閉塞及狹窄，未特定",        en: "Occlusion and stenosis of unspecified precerebral artery", cat: "心血管" },
  { code: "G45.9",   zh: "暫時性腦缺血發作，未特定",         en: "Transient cerebral ischemic attack, unspecified", cat: "心血管", kw: "TIA" },
  { code: "I73.9",   zh: "周邊血管疾病，未特定",            en: "Peripheral vascular disease, unspecified", cat: "心血管", kw: "PVD PAD" },
  { code: "I83.90",  zh: "無潰瘍或發炎之靜脈曲張",          en: "Asymptomatic varicose veins of unspecified lower extremity", cat: "心血管" },
  { code: "I87.2",   zh: "靜脈功能不全",                  en: "Venous insufficiency (chronic)", cat: "心血管" },
  { code: "I82.40",  zh: "急性深部靜脈栓塞，下肢未特定",      en: "Acute embolism and thrombosis of unspecified deep veins of lower extremity", cat: "心血管", kw: "DVT" },
  { code: "I26.99",  zh: "肺栓塞，無急性肺心病，未特定",      en: "Other pulmonary embolism without acute cor pulmonale", cat: "心血管", kw: "PE" },

  // ========== 呼吸系統 ==========
  { code: "J44.9",   zh: "慢性阻塞性肺病 (COPD)，未特定",   en: "COPD, unspecified", cat: "呼吸系統" },
  { code: "J44.1",   zh: "COPD 急性惡化",                 en: "COPD with acute exacerbation", cat: "呼吸系統" },
  { code: "J44.0",   zh: "COPD 伴急性下呼吸道感染",         en: "COPD with acute lower respiratory infection", cat: "呼吸系統" },
  { code: "J45.909", zh: "氣喘，未特定，無併發症",          en: "Unspecified asthma, uncomplicated", cat: "呼吸系統" },
  { code: "J45.901", zh: "氣喘，未特定，伴急性惡化",         en: "Unspecified asthma with (acute) exacerbation", cat: "呼吸系統" },
  { code: "J45.40",  zh: "中度持續性氣喘，無併發症",         en: "Moderate persistent asthma, uncomplicated", cat: "呼吸系統" },
  { code: "J45.30",  zh: "輕度持續性氣喘，無併發症",         en: "Mild persistent asthma, uncomplicated", cat: "呼吸系統" },
  { code: "J45.50",  zh: "重度持續性氣喘，無併發症",         en: "Severe persistent asthma, uncomplicated", cat: "呼吸系統" },
  { code: "J30.9",   zh: "過敏性鼻炎，未特定",              en: "Allergic rhinitis, unspecified", cat: "呼吸系統" },
  { code: "J30.1",   zh: "季節性過敏性鼻炎（花粉熱）",        en: "Allergic rhinitis due to pollen", cat: "呼吸系統" },
  { code: "J30.81",  zh: "過敏性鼻炎，食物過敏",            en: "Allergic rhinitis due to food", cat: "呼吸系統" },
  { code: "J30.89",  zh: "其他過敏性鼻炎",                 en: "Other allergic rhinitis", cat: "呼吸系統" },
  { code: "J31.0",   zh: "慢性鼻炎",                      en: "Chronic rhinitis", cat: "呼吸系統" },
  { code: "J00",     zh: "急性鼻咽炎（普通感冒）",           en: "Acute nasopharyngitis (common cold)", cat: "呼吸系統" },
  { code: "J02.9",   zh: "急性咽炎，未特定",               en: "Acute pharyngitis, unspecified", cat: "呼吸系統" },
  { code: "J03.90",  zh: "急性扁桃腺炎，未特定",            en: "Acute tonsillitis, unspecified", cat: "呼吸系統" },
  { code: "J04.0",   zh: "急性喉炎",                     en: "Acute laryngitis", cat: "呼吸系統" },
  { code: "J06.9",   zh: "急性上呼吸道感染，未特定",         en: "Acute upper respiratory infection, unspecified", cat: "呼吸系統", kw: "URI" },
  { code: "J20.9",   zh: "急性支氣管炎，未特定",            en: "Acute bronchitis, unspecified", cat: "呼吸系統" },
  { code: "J40",     zh: "支氣管炎，未區分急慢性",           en: "Bronchitis, not specified as acute or chronic", cat: "呼吸系統" },
  { code: "J42",     zh: "未特定之慢性支氣管炎",            en: "Unspecified chronic bronchitis", cat: "呼吸系統" },
  { code: "J32.9",   zh: "慢性鼻竇炎，未特定",              en: "Chronic sinusitis, unspecified", cat: "呼吸系統" },
  { code: "J01.90",  zh: "急性鼻竇炎，未特定",              en: "Acute sinusitis, unspecified", cat: "呼吸系統" },
  { code: "J11.1",   zh: "流行性感冒伴其他呼吸道症狀",        en: "Influenza with other respiratory manifestations", cat: "呼吸系統", kw: "flu" },
  { code: "J18.9",   zh: "肺炎，病原未特定",                en: "Pneumonia, unspecified organism", cat: "呼吸系統" },
  { code: "J15.9",   zh: "細菌性肺炎，未特定",              en: "Unspecified bacterial pneumonia", cat: "呼吸系統" },
  { code: "J12.9",   zh: "病毒性肺炎，未特定",              en: "Viral pneumonia, unspecified", cat: "呼吸系統" },
  { code: "J98.09",  zh: "其他氣道疾病，未分類在他處",        en: "Other diseases of bronchus, NEC", cat: "呼吸系統" },
  { code: "U07.1",   zh: "COVID-19，病毒已確認",           en: "COVID-19, virus identified", cat: "呼吸系統" },
  { code: "J96.90",  zh: "呼吸衰竭，未特定",               en: "Respiratory failure, unspecified, unspecified whether with hypoxia or hypercapnia", cat: "呼吸系統" },
  { code: "J98.4",   zh: "其他肺部疾病",                   en: "Other disorders of lung", cat: "呼吸系統" },

  // ========== 腎臟泌尿 ==========
  { code: "N18.1",   zh: "慢性腎病，第1期",                en: "CKD stage 1", cat: "腎臟泌尿" },
  { code: "N18.2",   zh: "慢性腎病，第2期（輕度）",         en: "CKD stage 2 (mild)", cat: "腎臟泌尿" },
  { code: "N18.30",  zh: "慢性腎病，第3期，未特定",         en: "CKD stage 3, unspecified", cat: "腎臟泌尿" },
  { code: "N18.31",  zh: "慢性腎病，第3a期",               en: "CKD stage 3a", cat: "腎臟泌尿" },
  { code: "N18.32",  zh: "慢性腎病，第3b期",               en: "CKD stage 3b", cat: "腎臟泌尿" },
  { code: "N18.4",   zh: "慢性腎病，第4期（重度）",         en: "CKD stage 4 (severe)", cat: "腎臟泌尿" },
  { code: "N18.5",   zh: "慢性腎病，第5期",                en: "CKD stage 5", cat: "腎臟泌尿" },
  { code: "N18.6",   zh: "末期腎病 (ESRD)",               en: "End stage renal disease", cat: "腎臟泌尿", kw: "ESRD" },
  { code: "N18.9",   zh: "慢性腎病，未特定",               en: "CKD, unspecified", cat: "腎臟泌尿" },
  { code: "N17.9",   zh: "急性腎衰竭，未特定",              en: "Acute kidney failure, unspecified", cat: "腎臟泌尿", kw: "AKI" },
  { code: "N39.0",   zh: "泌尿道感染，部位未特定",          en: "UTI, site not specified", cat: "腎臟泌尿", kw: "UTI" },
  { code: "N30.90",  zh: "膀胱炎，未特定，無血尿",           en: "Cystitis, unspecified without hematuria", cat: "腎臟泌尿" },
  { code: "N30.00",  zh: "急性膀胱炎，無血尿",              en: "Acute cystitis without hematuria", cat: "腎臟泌尿" },
  { code: "N10",     zh: "急性腎盂腎炎",                   en: "Acute pyelonephritis", cat: "腎臟泌尿" },
  { code: "N20.0",   zh: "腎結石",                        en: "Calculus of kidney", cat: "腎臟泌尿" },
  { code: "N20.1",   zh: "輸尿管結石",                    en: "Calculus of ureter", cat: "腎臟泌尿" },
  { code: "N40.0",   zh: "良性攝護腺肥大，無下泌尿道症狀",    en: "BPH without LUTS", cat: "腎臟泌尿", kw: "BPH" },
  { code: "N40.1",   zh: "良性攝護腺肥大，有下泌尿道症狀",    en: "BPH with LUTS", cat: "腎臟泌尿", kw: "BPH LUTS" },
  { code: "N41.9",   zh: "攝護腺發炎性疾病，未特定",         en: "Inflammatory disease of prostate, unspecified", cat: "腎臟泌尿" },
  { code: "N36.8",   zh: "其他尿道疾病",                   en: "Other specified disorders of urethra", cat: "腎臟泌尿" },
  { code: "R35.0",   zh: "頻尿",                         en: "Frequency of micturition", cat: "腎臟泌尿" },
  { code: "R30.0",   zh: "排尿困難",                      en: "Dysuria", cat: "腎臟泌尿" },
  { code: "R31.9",   zh: "血尿，未特定",                   en: "Hematuria, unspecified", cat: "腎臟泌尿" },
  { code: "R33.9",   zh: "尿滯留，未特定",                 en: "Retention of urine, unspecified", cat: "腎臟泌尿" },
  { code: "N39.41",  zh: "應力性尿失禁（女性）",             en: "Urge incontinence", cat: "腎臟泌尿" },
  { code: "N39.46",  zh: "混合型尿失禁",                   en: "Mixed incontinence", cat: "腎臟泌尿" },
  { code: "N13.30",  zh: "其他水腎症，未特定",              en: "Unspecified hydronephrosis", cat: "腎臟泌尿" },

  // ========== 內分泌代謝 ==========
  { code: "E03.9",   zh: "甲狀腺機能低下，未特定",           en: "Hypothyroidism, unspecified", cat: "內分泌代謝" },
  { code: "E03.8",   zh: "其他特定甲狀腺機能低下",           en: "Other specified hypothyroidism", cat: "內分泌代謝" },
  { code: "E05.90",  zh: "甲狀腺毒症，未特定，無甲狀腺風暴",   en: "Thyrotoxicosis, unspecified without thyrotoxic crisis", cat: "內分泌代謝" },
  { code: "E05.00",  zh: "葛瑞夫茲氏症，無甲狀腺風暴",       en: "Thyrotoxicosis with diffuse goiter without crisis", cat: "內分泌代謝", kw: "Graves" },
  { code: "E04.2",   zh: "非毒性多結節性甲狀腺腫",          en: "Nontoxic multinodular goiter", cat: "內分泌代謝" },
  { code: "E04.1",   zh: "非毒性單一甲狀腺結節",            en: "Nontoxic single thyroid nodule", cat: "內分泌代謝" },
  { code: "E06.3",   zh: "自體免疫性甲狀腺炎",              en: "Autoimmune thyroiditis", cat: "內分泌代謝", kw: "Hashimoto" },
  { code: "E66.9",   zh: "肥胖，未特定",                   en: "Obesity, unspecified", cat: "內分泌代謝" },
  { code: "E66.01",  zh: "病態性肥胖（因過多熱量）",         en: "Morbid (severe) obesity due to excess calories", cat: "內分泌代謝" },
  { code: "E66.3",   zh: "過重",                          en: "Overweight", cat: "內分泌代謝" },
  { code: "Z68.30",  zh: "BMI 30.0-30.9",                en: "Body mass index 30.0-30.9, adult", cat: "內分泌代謝" },
  { code: "Z68.35",  zh: "BMI 35.0-35.9",                en: "Body mass index 35.0-35.9, adult", cat: "內分泌代謝" },
  { code: "M10.9",   zh: "痛風，未特定",                   en: "Gout, unspecified", cat: "內分泌代謝" },
  { code: "M10.00",  zh: "原發性痛風，未特定部位",          en: "Idiopathic gout, unspecified site", cat: "內分泌代謝" },
  { code: "E79.0",   zh: "高尿酸血症，無發炎性關節炎及痛風石", en: "Hyperuricemia without signs of inflammatory arthritis and tophaceous disease", cat: "內分泌代謝" },
  { code: "E55.9",   zh: "維生素D缺乏，未特定",             en: "Vitamin D deficiency, unspecified", cat: "內分泌代謝" },
  { code: "E61.1",   zh: "鐵缺乏",                        en: "Iron deficiency", cat: "內分泌代謝" },
  { code: "E50.9",   zh: "維生素A缺乏，未特定",             en: "Vitamin A deficiency, unspecified", cat: "內分泌代謝" },
  { code: "E53.8",   zh: "其他特定維生素B缺乏",              en: "Deficiency of other specified B group vitamins", cat: "內分泌代謝" },
  { code: "E56.9",   zh: "維生素缺乏，未特定",              en: "Vitamin deficiency, unspecified", cat: "內分泌代謝" },
  { code: "E83.42",  zh: "低鎂血症",                      en: "Hypomagnesemia", cat: "內分泌代謝" },
  { code: "E87.6",   zh: "低鉀血症",                      en: "Hypokalemia", cat: "內分泌代謝" },
  { code: "E87.5",   zh: "高鉀血症",                      en: "Hyperkalemia", cat: "內分泌代謝" },
  { code: "E87.1",   zh: "低血鈉症（稀釋性低血鈉）",         en: "Hypo-osmolality and hyponatremia", cat: "內分泌代謝" },
  { code: "E87.0",   zh: "高血鈉症",                      en: "Hyperosmolality and hypernatremia", cat: "內分泌代謝" },
  { code: "E86.0",   zh: "脫水",                          en: "Dehydration", cat: "內分泌代謝" },
  { code: "E28.2",   zh: "多囊性卵巢症候群",               en: "Polycystic ovarian syndrome", cat: "內分泌代謝", kw: "PCOS" },

  // ========== 骨骼肌肉 ==========
  { code: "M81.0",   zh: "老年性骨質疏鬆，無現行病理性骨折",  en: "Age-related osteoporosis without current pathological fracture", cat: "骨骼肌肉" },
  { code: "M80.00",  zh: "老年性骨質疏鬆伴現行病理性骨折，未特定部位", en: "Age-related osteoporosis with current pathological fracture, unspecified site", cat: "骨骼肌肉" },
  { code: "M85.80",  zh: "其他特定之骨密度及結構異常",        en: "Other specified disorders of bone density and structure", cat: "骨骼肌肉" },
  { code: "M89.9",   zh: "骨病變，未特定",                  en: "Disorder of bone, unspecified", cat: "骨骼肌肉" },
  { code: "M54.50",  zh: "下背痛，未特定",                 en: "Low back pain, unspecified", cat: "骨骼肌肉", kw: "LBP" },
  { code: "M54.51",  zh: "椎源性下背痛",                   en: "Vertebrogenic low back pain", cat: "骨骼肌肉" },
  { code: "M54.2",   zh: "頸痛",                         en: "Cervicalgia", cat: "骨骼肌肉" },
  { code: "M54.9",   zh: "背痛，未特定",                  en: "Dorsalgia, unspecified", cat: "骨骼肌肉" },
  { code: "M54.17",  zh: "腰薦神經根病變",                 en: "Radiculopathy, lumbosacral region", cat: "骨骼肌肉" },
  { code: "M54.16",  zh: "腰神經根病變",                   en: "Radiculopathy, lumbar region", cat: "骨骼肌肉" },
  { code: "M54.12",  zh: "頸神經根病變",                   en: "Radiculopathy, cervical region", cat: "骨骼肌肉" },
  { code: "M25.50",  zh: "關節疼痛，未特定關節",            en: "Pain in unspecified joint", cat: "骨骼肌肉" },
  { code: "M25.561", zh: "右膝疼痛",                     en: "Pain in right knee", cat: "骨骼肌肉" },
  { code: "M25.562", zh: "左膝疼痛",                     en: "Pain in left knee", cat: "骨骼肌肉" },
  { code: "M25.569", zh: "膝疼痛，未特定側",                en: "Pain in unspecified knee", cat: "骨骼肌肉" },
  { code: "M25.511", zh: "右肩疼痛",                     en: "Pain in right shoulder", cat: "骨骼肌肉" },
  { code: "M25.512", zh: "左肩疼痛",                     en: "Pain in left shoulder", cat: "骨骼肌肉" },
  { code: "M25.551", zh: "右髖疼痛",                     en: "Pain in right hip", cat: "骨骼肌肉" },
  { code: "M25.552", zh: "左髖疼痛",                     en: "Pain in left hip", cat: "骨骼肌肉" },
  { code: "M17.9",   zh: "膝關節退化性關節炎，未特定",        en: "Osteoarthritis of knee, unspecified", cat: "骨骼肌肉", kw: "knee OA" },
  { code: "M17.11",  zh: "右膝原發性退化性關節炎",           en: "Unilateral primary osteoarthritis, right knee", cat: "骨骼肌肉" },
  { code: "M17.12",  zh: "左膝原發性退化性關節炎",           en: "Unilateral primary osteoarthritis, left knee", cat: "骨骼肌肉" },
  { code: "M16.9",   zh: "髖關節退化性關節炎，未特定",        en: "Osteoarthritis of hip, unspecified", cat: "骨骼肌肉" },
  { code: "M19.90",  zh: "退化性關節炎，未特定部位",         en: "Unspecified osteoarthritis, unspecified site", cat: "骨骼肌肉" },
  { code: "M79.10",  zh: "肌痛，部位未特定",               en: "Myalgia, unspecified site", cat: "骨骼肌肉" },
  { code: "M79.1",   zh: "肌痛",                         en: "Myalgia", cat: "骨骼肌肉" },
  { code: "M79.7",   zh: "纖維肌痛症",                   en: "Fibromyalgia", cat: "骨骼肌肉" },
  { code: "M62.81",  zh: "肌肉無力（全身性）",              en: "Muscle weakness (generalized)", cat: "骨骼肌肉" },
  { code: "M47.812", zh: "頸椎脊椎關節病，無脊髓或神經根病變", en: "Cervical spondylosis without myelopathy or radiculopathy", cat: "骨骼肌肉" },
  { code: "M47.817", zh: "腰薦椎脊椎關節病，無脊髓或神經根病變", en: "Lumbosacral spondylosis without myelopathy or radiculopathy", cat: "骨骼肌肉" },
  { code: "M51.26",  zh: "其他椎間盤移位，腰椎",             en: "Other intervertebral disc displacement, lumbar region", cat: "骨骼肌肉" },
  { code: "M51.27",  zh: "其他椎間盤移位，腰薦椎",            en: "Other intervertebral disc displacement, lumbosacral region", cat: "骨骼肌肉" },
  { code: "M75.100", zh: "肩旋轉肌袖症候群，未特定",         en: "Unspecified rotator cuff tear, not specified as traumatic", cat: "骨骼肌肉" },
  { code: "M75.30",  zh: "肩鈣化性肌腱炎，未特定肩",         en: "Calcific tendinitis of unspecified shoulder", cat: "骨骼肌肉" },
  { code: "M77.00",  zh: "內上髁炎，未特定手肘",             en: "Medial epicondylitis, unspecified elbow", cat: "骨骼肌肉", kw: "golfer's elbow" },
  { code: "M77.10",  zh: "外上髁炎，未特定手肘",             en: "Lateral epicondylitis, unspecified elbow", cat: "骨骼肌肉", kw: "tennis elbow" },
  { code: "M77.9",   zh: "肌腱端病變，未特定",              en: "Enthesopathy, unspecified", cat: "骨骼肌肉" },
  { code: "M77.30",  zh: "跟骨骨刺，未特定足",              en: "Calcaneal spur, unspecified foot", cat: "骨骼肌肉" },
  { code: "M77.40",  zh: "足底筋膜炎，未特定足",            en: "Metatarsalgia, unspecified foot", cat: "骨骼肌肉" },
  { code: "M72.2",   zh: "足底筋膜纖維瘤病",                en: "Plantar fascial fibromatosis", cat: "骨骼肌肉", kw: "plantar fasciitis" },
  { code: "M65.30",  zh: "扳機指，未特定手指",              en: "Trigger finger, unspecified finger", cat: "骨骼肌肉" },
  { code: "M65.4",   zh: "橈骨莖突狹窄性腱鞘炎",            en: "Radial styloid tenosynovitis", cat: "骨骼肌肉", kw: "De Quervain" },
  { code: "M06.9",   zh: "類風濕性關節炎，未特定",           en: "Rheumatoid arthritis, unspecified", cat: "骨骼肌肉", kw: "RA" },

  // ========== 精神/睡眠 ==========
  { code: "F32.9",   zh: "重度憂鬱症，單次發作，未特定",       en: "Major depressive disorder, single episode, unspecified", cat: "精神/睡眠", kw: "MDD depression" },
  { code: "F32.A",   zh: "憂鬱症，未特定",                 en: "Depression, unspecified", cat: "精神/睡眠" },
  { code: "F32.0",   zh: "重度憂鬱症，單次發作，輕度",        en: "MDD, single episode, mild", cat: "精神/睡眠" },
  { code: "F32.1",   zh: "重度憂鬱症，單次發作，中度",        en: "MDD, single episode, moderate", cat: "精神/睡眠" },
  { code: "F32.2",   zh: "重度憂鬱症，單次發作，重度，無精神症狀", en: "MDD, single episode, severe without psychotic features", cat: "精神/睡眠" },
  { code: "F33.9",   zh: "重度憂鬱症，復發，未特定",         en: "Major depressive disorder, recurrent, unspecified", cat: "精神/睡眠" },
  { code: "F33.0",   zh: "重度憂鬱症，復發，輕度",           en: "MDD, recurrent, mild", cat: "精神/睡眠" },
  { code: "F34.1",   zh: "輕鬱症",                        en: "Dysthymic disorder", cat: "精神/睡眠" },
  { code: "F41.1",   zh: "廣泛性焦慮症",                   en: "Generalized anxiety disorder", cat: "精神/睡眠", kw: "GAD anxiety" },
  { code: "F41.9",   zh: "焦慮症，未特定",                 en: "Anxiety disorder, unspecified", cat: "精神/睡眠" },
  { code: "F41.0",   zh: "恐慌症",                        en: "Panic disorder", cat: "精神/睡眠" },
  { code: "F41.8",   zh: "其他特定焦慮症",                 en: "Other specified anxiety disorders", cat: "精神/睡眠" },
  { code: "F40.10",  zh: "社交焦慮症，未特定",              en: "Social anxiety disorder, unspecified", cat: "精神/睡眠" },
  { code: "F40.9",   zh: "恐懼症，未特定",                 en: "Phobic anxiety disorder, unspecified", cat: "精神/睡眠" },
  { code: "F42.9",   zh: "強迫症，未特定",                 en: "Obsessive-compulsive disorder, unspecified", cat: "精神/睡眠", kw: "OCD" },
  { code: "F43.10",  zh: "創傷後壓力症候群，未特定",         en: "Post-traumatic stress disorder, unspecified", cat: "精神/睡眠", kw: "PTSD" },
  { code: "F43.20",  zh: "適應障礙，未特定",                en: "Adjustment disorder, unspecified", cat: "精神/睡眠" },
  { code: "F43.23",  zh: "適應障礙伴混合焦慮及憂鬱情緒",      en: "Adjustment disorder with mixed anxiety and depressed mood", cat: "精神/睡眠" },
  { code: "F43.9",   zh: "重大壓力反應，未特定",             en: "Reaction to severe stress, unspecified", cat: "精神/睡眠" },
  { code: "G47.00",  zh: "失眠，未特定",                   en: "Insomnia, unspecified", cat: "精神/睡眠" },
  { code: "G47.01",  zh: "原發性失眠",                     en: "Insomnia due to medical condition", cat: "精神/睡眠" },
  { code: "F51.01",  zh: "原發性失眠",                     en: "Primary insomnia", cat: "精神/睡眠" },
  { code: "G47.33",  zh: "阻塞性睡眠呼吸中止（成人）",        en: "Obstructive sleep apnea (adult)", cat: "精神/睡眠", kw: "OSA" },
  { code: "G47.30",  zh: "睡眠呼吸中止，未特定",            en: "Sleep apnea, unspecified", cat: "精神/睡眠" },
  { code: "G47.9",   zh: "睡眠疾患，未特定",                en: "Sleep disorder, unspecified", cat: "精神/睡眠" },
  { code: "F03.90",  zh: "失智症，未特定，無行為障礙",        en: "Unspecified dementia, unspecified severity, without behavioral disturbance", cat: "精神/睡眠" },
  { code: "F03.91",  zh: "失智症，未特定，伴行為障礙",        en: "Unspecified dementia, unspecified severity, with behavioral disturbance", cat: "精神/睡眠" },
  { code: "G30.9",   zh: "阿茲海默症，未特定",               en: "Alzheimer's disease, unspecified", cat: "精神/睡眠" },
  { code: "F01.50",  zh: "血管性失智症，無行為障礙",         en: "Vascular dementia, unspecified severity, without behavioral disturbance", cat: "精神/睡眠" },
  { code: "F10.20",  zh: "酒精依賴，未併發",                en: "Alcohol dependence, uncomplicated", cat: "精神/睡眠" },
  { code: "F10.10",  zh: "酒精濫用，未併發",                en: "Alcohol abuse, uncomplicated", cat: "精神/睡眠" },
  { code: "Z63.0",   zh: "與配偶或伴侶關係問題",             en: "Problems in relationship with spouse or partner", cat: "精神/睡眠" },
  { code: "Z63.4",   zh: "家庭成員消失或死亡",               en: "Disappearance and death of family member", cat: "精神/睡眠" },

  // ========== 消化系統 ==========
  { code: "K21.9",   zh: "胃食道逆流，無食道炎",             en: "GERD without esophagitis", cat: "消化系統", kw: "GERD" },
  { code: "K21.0",   zh: "胃食道逆流，伴食道炎",             en: "GERD with esophagitis", cat: "消化系統" },
  { code: "K29.70",  zh: "胃炎，未特定，無出血",             en: "Gastritis, unspecified, without bleeding", cat: "消化系統" },
  { code: "K29.00",  zh: "急性胃炎，無出血",                en: "Acute gastritis without bleeding", cat: "消化系統" },
  { code: "K29.50",  zh: "慢性胃炎，未特定，無出血",         en: "Unspecified chronic gastritis without bleeding", cat: "消化系統" },
  { code: "K25.9",   zh: "胃潰瘍，未特定（急或慢），無出血或穿孔", en: "Gastric ulcer, unspecified as acute or chronic, without hemorrhage or perforation", cat: "消化系統" },
  { code: "K26.9",   zh: "十二指腸潰瘍，未特定（急或慢），無出血或穿孔", en: "Duodenal ulcer, unspecified as acute or chronic, without hemorrhage or perforation", cat: "消化系統" },
  { code: "K30",     zh: "功能性消化不良",                 en: "Functional dyspepsia", cat: "消化系統" },
  { code: "K31.9",   zh: "胃及十二指腸疾病，未特定",          en: "Disease of stomach and duodenum, unspecified", cat: "消化系統" },
  { code: "K57.30",  zh: "大腸憩室症，無穿孔或膿瘍，無出血",    en: "Diverticulosis of large intestine without perforation or abscess without bleeding", cat: "消化系統" },
  { code: "K57.92",  zh: "大腸憩室炎",                     en: "Diverticulitis of intestine, part unspecified, without perforation or abscess without bleeding", cat: "消化系統" },
  { code: "K58.9",   zh: "腸躁症，無腹瀉",                 en: "Irritable bowel syndrome without diarrhea", cat: "消化系統", kw: "IBS" },
  { code: "K58.0",   zh: "腸躁症伴腹瀉",                   en: "Irritable bowel syndrome with diarrhea", cat: "消化系統" },
  { code: "K58.1",   zh: "腸躁症伴便秘",                   en: "Irritable bowel syndrome with constipation", cat: "消化系統" },
  { code: "K59.00",  zh: "便秘，未特定",                  en: "Constipation, unspecified", cat: "消化系統" },
  { code: "K59.01",  zh: "慢性功能性便秘",                 en: "Slow transit constipation", cat: "消化系統" },
  { code: "K52.9",   zh: "非感染性胃腸炎及結腸炎，未特定",     en: "Noninfective gastroenteritis and colitis, unspecified", cat: "消化系統" },
  { code: "K59.1",   zh: "功能性腹瀉",                     en: "Functional diarrhea", cat: "消化系統" },
  { code: "K76.0",   zh: "脂肪肝，未分類在他處",             en: "Fatty (change of) liver, NEC", cat: "消化系統", kw: "NAFLD" },
  { code: "K75.81",  zh: "非酒精性脂肪肝炎",                en: "Nonalcoholic steatohepatitis", cat: "消化系統", kw: "NASH" },
  { code: "K73.9",   zh: "慢性肝炎，未特定",                en: "Chronic hepatitis, unspecified", cat: "消化系統" },
  { code: "B18.2",   zh: "慢性病毒性C型肝炎",              en: "Chronic viral hepatitis C", cat: "消化系統", kw: "HCV" },
  { code: "B18.1",   zh: "慢性病毒性B型肝炎，無D因子",       en: "Chronic viral hepatitis B without delta agent", cat: "消化系統", kw: "HBV" },
  { code: "K74.60",  zh: "肝硬化，未特定",                  en: "Unspecified cirrhosis of liver", cat: "消化系統" },
  { code: "K80.20",  zh: "膽結石，無膽囊炎，無阻塞",         en: "Calculus of gallbladder without cholecystitis without obstruction", cat: "消化系統" },
  { code: "K80.50",  zh: "膽管結石，無膽管炎或膽囊炎，無阻塞", en: "Calculus of bile duct without cholangitis or cholecystitis without obstruction", cat: "消化系統" },
  { code: "K81.9",   zh: "膽囊炎，未特定",                  en: "Cholecystitis, unspecified", cat: "消化系統" },
  { code: "K82.8",   zh: "膽囊其他特定疾病",                en: "Other specified diseases of gallbladder", cat: "消化系統" },
  { code: "K86.1",   zh: "其他慢性胰臟炎",                  en: "Other chronic pancreatitis", cat: "消化系統" },
  { code: "K85.90",  zh: "急性胰臟炎，未特定，無壞死或感染",   en: "Acute pancreatitis without necrosis or infection, unspecified", cat: "消化系統" },
  { code: "K64.9",   zh: "痔瘡，未特定",                   en: "Unspecified hemorrhoids", cat: "消化系統" },
  { code: "K64.8",   zh: "其他痔瘡",                      en: "Other hemorrhoids", cat: "消化系統" },
  { code: "K50.90",  zh: "克隆氏症，未特定，無併發症",       en: "Crohn's disease, unspecified, without complications", cat: "消化系統" },
  { code: "K51.90",  zh: "潰瘍性結腸炎，未特定，無併發症",    en: "Ulcerative colitis, unspecified, without complications", cat: "消化系統" },

  // ========== 神經系統 ==========
  { code: "G43.909", zh: "偏頭痛，未特定，無難治性且無偏頭痛狀態", en: "Migraine, unspecified, not intractable, without status migrainosus", cat: "神經系統" },
  { code: "G43.009", zh: "無先兆偏頭痛，未特定",             en: "Migraine without aura, not intractable", cat: "神經系統" },
  { code: "G43.109", zh: "伴先兆偏頭痛，未特定",             en: "Migraine with aura, not intractable", cat: "神經系統" },
  { code: "G44.209", zh: "緊張型頭痛，未特定，無難治性",      en: "Tension-type headache, unspecified, not intractable", cat: "神經系統" },
  { code: "G44.1",   zh: "血管性頭痛，未分類在他處",         en: "Vascular headache, NEC", cat: "神經系統" },
  { code: "R51.9",   zh: "頭痛，未特定",                  en: "Headache, unspecified", cat: "神經系統" },
  { code: "G62.9",   zh: "多發性神經病變，未特定",           en: "Polyneuropathy, unspecified", cat: "神經系統" },
  { code: "G56.00",  zh: "腕隧道症候群，未特定上肢",         en: "Carpal tunnel syndrome, unspecified upper limb", cat: "神經系統", kw: "CTS" },
  { code: "G56.01",  zh: "右手腕隧道症候群",                en: "Carpal tunnel syndrome, right upper limb", cat: "神經系統" },
  { code: "G56.02",  zh: "左手腕隧道症候群",                en: "Carpal tunnel syndrome, left upper limb", cat: "神經系統" },
  { code: "G57.00",  zh: "坐骨神經病變，未特定下肢",         en: "Lesion of sciatic nerve, unspecified lower limb", cat: "神經系統" },
  { code: "G20",     zh: "帕金森氏症",                     en: "Parkinson's disease", cat: "神經系統" },
  { code: "G25.0",   zh: "原發性震顫",                     en: "Essential tremor", cat: "神經系統" },
  { code: "R42",     zh: "頭暈及眩暈",                     en: "Dizziness and giddiness", cat: "神經系統" },
  { code: "H81.10",  zh: "良性陣發性眩暈，未特定耳",         en: "Benign paroxysmal vertigo, unspecified ear", cat: "神經系統", kw: "BPPV" },
  { code: "H81.09",  zh: "梅尼爾氏症，未特定耳",             en: "Meniere's disease, unspecified ear", cat: "神經系統" },
  { code: "G40.909", zh: "癲癇，未特定，無難治性，無癲癇重積", en: "Epilepsy, unspecified, not intractable, without status epilepticus", cat: "神經系統" },
  { code: "G40.409", zh: "其他全身性癲癇及癲癇症候群",        en: "Other generalized epilepsy and epileptic syndromes", cat: "神經系統" },
  { code: "G51.0",   zh: "貝爾氏麻痹（顏面神經麻痹）",       en: "Bell's palsy", cat: "神經系統" },
  { code: "G50.1",   zh: "非典型顏面痛",                  en: "Atypical facial pain", cat: "神經系統" },
  { code: "G50.0",   zh: "三叉神經痛",                    en: "Trigeminal neuralgia", cat: "神經系統" },
  { code: "R47.01",  zh: "失語症",                       en: "Aphasia", cat: "神經系統" },
  { code: "R26.81",  zh: "步態不穩",                      en: "Unsteadiness on feet", cat: "神經系統" },

  // ========== 健檢/預防 ==========
  { code: "Z00.00",  zh: "一般成人健康檢查，無異常發現",       en: "Encounter for general adult medical exam without abnormal findings", cat: "健檢/預防" },
  { code: "Z00.01",  zh: "一般成人健康檢查，有異常發現",       en: "Encounter for general adult medical exam with abnormal findings", cat: "健檢/預防" },
  { code: "Z00.129", zh: "兒童例行健康檢查，無異常發現",       en: "Encounter for routine child health examination without abnormal findings", cat: "健檢/預防" },
  { code: "Z13.1",   zh: "糖尿病篩檢",                    en: "Encounter for screening for diabetes mellitus", cat: "健檢/預防" },
  { code: "Z13.220", zh: "血脂代謝異常篩檢",                en: "Encounter for screening for lipoid disorders", cat: "健檢/預防" },
  { code: "Z13.6",   zh: "心血管疾病篩檢",                 en: "Encounter for screening for cardiovascular disorders", cat: "健檢/預防" },
  { code: "Z13.9",   zh: "疾病篩檢，未特定",                en: "Encounter for screening, unspecified", cat: "健檢/預防" },
  { code: "Z13.39",  zh: "精神健康及行為疾患篩檢",            en: "Encounter for screening examination for other mental health and behavioral disorders", cat: "健檢/預防" },
  { code: "Z13.83",  zh: "呼吸系統疾病篩檢",                en: "Encounter for screening for respiratory disorder", cat: "健檢/預防" },
  { code: "Z13.88",  zh: "其他消化系統疾病篩檢",             en: "Encounter for screening for disorder due to exposure to contaminants", cat: "健檢/預防" },
  { code: "Z12.11",  zh: "大腸癌篩檢",                    en: "Encounter for screening for malignant neoplasm of colon", cat: "健檢/預防" },
  { code: "Z12.12",  zh: "直腸癌篩檢",                    en: "Encounter for screening for malignant neoplasm of rectum", cat: "健檢/預防" },
  { code: "Z12.31",  zh: "乳房攝影篩檢",                   en: "Encounter for screening mammogram for malignant neoplasm of breast", cat: "健檢/預防" },
  { code: "Z12.39",  zh: "其他乳房惡性腫瘤篩檢",             en: "Encounter for other screening for malignant neoplasm of breast", cat: "健檢/預防" },
  { code: "Z12.4",   zh: "子宮頸癌篩檢",                   en: "Encounter for screening for malignant neoplasm of cervix", cat: "健檢/預防" },
  { code: "Z12.72",  zh: "陰道癌篩檢",                    en: "Encounter for screening for malignant neoplasm of vagina", cat: "健檢/預防" },
  { code: "Z12.9",   zh: "腫瘤篩檢，未特定",                en: "Encounter for screening for malignant neoplasm, site unspecified", cat: "健檢/預防" },
  { code: "Z11.3",   zh: "性傳播感染篩檢",                 en: "Encounter for screening for infections with a predominantly sexual mode of transmission", cat: "健檢/預防" },
  { code: "Z11.4",   zh: "人類免疫缺乏病毒 (HIV) 篩檢",      en: "Encounter for screening for HIV", cat: "健檢/預防" },
  { code: "Z23",     zh: "疫苗接種",                      en: "Encounter for immunization", cat: "健檢/預防" },
  { code: "Z71.3",   zh: "飲食諮詢與衛教",                 en: "Dietary counseling and surveillance", cat: "健檢/預防" },
  { code: "Z71.82",  zh: "運動諮詢",                      en: "Exercise counseling", cat: "健檢/預防" },
  { code: "Z71.6",   zh: "菸草濫用諮詢",                  en: "Tobacco abuse counseling", cat: "健檢/預防" },
  { code: "Z71.41",  zh: "酒精濫用諮詢及監督",              en: "Alcohol abuse counseling and surveillance of alcoholic", cat: "健檢/預防" },
  { code: "Z72.0",   zh: "使用菸草",                      en: "Tobacco use", cat: "健檢/預防" },
  { code: "F17.200", zh: "尼古丁依賴，未特定，無併發症",      en: "Nicotine dependence, unspecified, uncomplicated", cat: "健檢/預防" },
  { code: "F17.210", zh: "尼古丁依賴，菸草，無併發症",        en: "Nicotine dependence, cigarettes, uncomplicated", cat: "健檢/預防" },
  { code: "Z68.1",   zh: "成人 BMI 19.9 或以下",          en: "BMI 19.9 or less, adult", cat: "健檢/預防" },
  { code: "Z68.20",  zh: "成人 BMI 20.0-20.9",           en: "BMI 20.0-20.9, adult", cat: "健檢/預防" },
  { code: "Z68.25",  zh: "成人 BMI 25.0-25.9",           en: "BMI 25.0-25.9, adult", cat: "健檢/預防" },
  { code: "Z79.899", zh: "其他長期藥物治療",                en: "Other long term (current) drug therapy", cat: "健檢/預防" },
  { code: "Z79.01",  zh: "長期使用抗凝血劑",                en: "Long term (current) use of anticoagulants", cat: "健檢/預防" },
  { code: "Z79.02",  zh: "長期使用抗血小板/抗凝血",          en: "Long term (current) use of antithrombotics/antiplatelets", cat: "健檢/預防" },
  { code: "Z79.82",  zh: "長期使用阿斯匹靈",                en: "Long term (current) use of aspirin", cat: "健檢/預防" },
  { code: "Z79.891", zh: "長期使用鴉片類藥物",              en: "Long term (current) use of opiate analgesic", cat: "健檢/預防" },
  { code: "Z87.891", zh: "個人史：尼古丁依賴",              en: "Personal history of nicotine dependence", cat: "健檢/預防" },
  { code: "Z86.39",  zh: "個人史：其他內分泌、營養及代謝疾病", en: "Personal history of other endocrine, nutritional and metabolic disease", cat: "健檢/預防" },
  { code: "Z85.3",   zh: "個人史：乳房惡性腫瘤",             en: "Personal history of malignant neoplasm of breast", cat: "健檢/預防" },

  // ========== 常見症狀 ==========
  { code: "R10.9",   zh: "腹痛，未特定",                   en: "Unspecified abdominal pain", cat: "常見症狀" },
  { code: "R10.13",  zh: "上腹痛",                        en: "Epigastric pain", cat: "常見症狀" },
  { code: "R10.30",  zh: "下腹痛，未特定",                 en: "Lower abdominal pain, unspecified", cat: "常見症狀" },
  { code: "R10.31",  zh: "右下腹痛",                      en: "Right lower quadrant pain", cat: "常見症狀" },
  { code: "R10.32",  zh: "左下腹痛",                      en: "Left lower quadrant pain", cat: "常見症狀" },
  { code: "R10.11",  zh: "右上腹痛",                      en: "Right upper quadrant pain", cat: "常見症狀" },
  { code: "R10.12",  zh: "左上腹痛",                      en: "Left upper quadrant pain", cat: "常見症狀" },
  { code: "R10.2",   zh: "骨盆及會陰疼痛",                 en: "Pelvic and perineal pain", cat: "常見症狀" },
  { code: "R10.84",  zh: "瀰漫性腹痛",                    en: "Generalized abdominal pain", cat: "常見症狀" },
  { code: "R05.9",   zh: "咳嗽，未特定",                   en: "Cough, unspecified", cat: "常見症狀" },
  { code: "R05.1",   zh: "急性咳嗽",                      en: "Acute cough", cat: "常見症狀" },
  { code: "R05.3",   zh: "慢性咳嗽",                      en: "Chronic cough", cat: "常見症狀" },
  { code: "R50.9",   zh: "發燒，未特定",                   en: "Fever, unspecified", cat: "常見症狀" },
  { code: "R50.82",  zh: "產後發燒",                      en: "Postprocedural fever", cat: "常見症狀" },
  { code: "R07.9",   zh: "胸痛，未特定",                   en: "Chest pain, unspecified", cat: "常見症狀" },
  { code: "R07.89",  zh: "其他胸痛",                      en: "Other chest pain", cat: "常見症狀" },
  { code: "R07.2",   zh: "心前區疼痛",                    en: "Precordial pain", cat: "常見症狀" },
  { code: "R11.2",   zh: "噁心伴嘔吐，未特定",              en: "Nausea with vomiting, unspecified", cat: "常見症狀" },
  { code: "R11.10",  zh: "嘔吐，未特定",                   en: "Vomiting, unspecified", cat: "常見症狀" },
  { code: "R11.0",   zh: "噁心",                         en: "Nausea", cat: "常見症狀" },
  { code: "R19.7",   zh: "腹瀉，未特定",                   en: "Diarrhea, unspecified", cat: "常見症狀" },
  { code: "R53.83",  zh: "其他疲倦",                      en: "Other fatigue", cat: "常見症狀" },
  { code: "R53.81",  zh: "其他全身不適",                   en: "Other malaise", cat: "常見症狀" },
  { code: "R60.0",   zh: "局部水腫",                      en: "Localized edema", cat: "常見症狀" },
  { code: "R60.9",   zh: "水腫，未特定",                   en: "Edema, unspecified", cat: "常見症狀" },
  { code: "R63.4",   zh: "體重減輕異常",                   en: "Abnormal weight loss", cat: "常見症狀" },
  { code: "R63.5",   zh: "體重增加異常",                   en: "Abnormal weight gain", cat: "常見症狀" },
  { code: "R63.0",   zh: "食慾不振",                      en: "Anorexia", cat: "常見症狀" },
  { code: "R63.3",   zh: "餵食困難",                      en: "Feeding difficulties", cat: "常見症狀" },
  { code: "R73.9",   zh: "高血糖，未特定",                 en: "Hyperglycemia, unspecified", cat: "常見症狀" },
  { code: "R06.02",  zh: "呼吸短促",                      en: "Shortness of breath", cat: "常見症狀" },
  { code: "R06.00",  zh: "呼吸困難，未特定",               en: "Dyspnea, unspecified", cat: "常見症狀" },
  { code: "R06.2",   zh: "喘鳴",                         en: "Wheezing", cat: "常見症狀" },
  { code: "R41.0",   zh: "定向感障礙",                    en: "Disorientation, unspecified", cat: "常見症狀" },
  { code: "R41.3",   zh: "近期記憶力減退",                 en: "Other amnesia", cat: "常見症狀" },
  { code: "R41.841", zh: "認知障礙",                      en: "Cognitive communication deficit", cat: "常見症狀" },
  { code: "R45.0",   zh: "神經質",                        en: "Nervousness", cat: "常見症狀" },
  { code: "R45.1",   zh: "不安及焦躁",                    en: "Restlessness and agitation", cat: "常見症狀" },

  // ========== 皮膚 ==========
  { code: "L20.9",   zh: "異位性皮膚炎，未特定",             en: "Atopic dermatitis, unspecified", cat: "皮膚" },
  { code: "L23.9",   zh: "過敏性接觸性皮膚炎，原因未特定",     en: "Allergic contact dermatitis, unspecified cause", cat: "皮膚" },
  { code: "L24.9",   zh: "刺激性接觸性皮膚炎，原因未特定",     en: "Irritant contact dermatitis, unspecified cause", cat: "皮膚" },
  { code: "L25.9",   zh: "接觸性皮膚炎，原因未特定",          en: "Unspecified contact dermatitis, unspecified cause", cat: "皮膚" },
  { code: "L29.9",   zh: "搔癢，未特定",                   en: "Pruritus, unspecified", cat: "皮膚" },
  { code: "L40.9",   zh: "乾癬，未特定",                   en: "Psoriasis, unspecified", cat: "皮膚" },
  { code: "L30.9",   zh: "皮膚炎，未特定",                 en: "Dermatitis, unspecified", cat: "皮膚" },
  { code: "L30.0",   zh: "錢幣狀皮膚炎",                   en: "Nummular dermatitis", cat: "皮膚" },
  { code: "L50.9",   zh: "蕁麻疹，未特定",                 en: "Urticaria, unspecified", cat: "皮膚" },
  { code: "L50.0",   zh: "過敏性蕁麻疹",                   en: "Allergic urticaria", cat: "皮膚" },
  { code: "L70.0",   zh: "尋常性痤瘡（青春痘）",             en: "Acne vulgaris", cat: "皮膚" },
  { code: "L70.9",   zh: "痤瘡，未特定",                   en: "Acne, unspecified", cat: "皮膚" },
  { code: "L71.9",   zh: "酒渣性皮膚炎，未特定",             en: "Rosacea, unspecified", cat: "皮膚" },
  { code: "L72.0",   zh: "皮脂腺囊腫",                     en: "Epidermal cyst", cat: "皮膚" },
  { code: "L73.2",   zh: "化膿性汗腺炎",                   en: "Hidradenitis suppurativa", cat: "皮膚" },
  { code: "L84",     zh: "雞眼及繭",                      en: "Corns and callosities", cat: "皮膚" },
  { code: "B02.9",   zh: "帶狀皰疹，無併發症",              en: "Zoster without complications", cat: "皮膚" },
  { code: "B00.9",   zh: "單純皰疹，未特定",                en: "Herpesviral infection, unspecified", cat: "皮膚" },
  { code: "B35.1",   zh: "指甲真菌感染（灰指甲）",           en: "Tinea unguium", cat: "皮膚" },
  { code: "B35.3",   zh: "足癬",                         en: "Tinea pedis", cat: "皮膚" },
  { code: "B35.4",   zh: "體癬",                         en: "Tinea corporis", cat: "皮膚" },
  { code: "B35.6",   zh: "股癬",                         en: "Tinea cruris", cat: "皮膚" },
  { code: "B37.2",   zh: "皮膚及指甲念珠菌感染",            en: "Candidiasis of skin and nail", cat: "皮膚" },
  { code: "L02.91",  zh: "皮膚膿瘍，未特定",                en: "Cutaneous abscess, unspecified", cat: "皮膚" },
  { code: "L03.90",  zh: "蜂窩組織炎，未特定",              en: "Cellulitis, unspecified", cat: "皮膚" },
  { code: "L04.9",   zh: "急性淋巴結炎，未特定",            en: "Acute lymphadenitis, unspecified", cat: "皮膚" },
  { code: "L98.9",   zh: "皮膚及皮下組織疾病，未特定",        en: "Disorder of the skin and subcutaneous tissue, unspecified", cat: "皮膚" },

  // ========== 感染症 ==========
  { code: "A08.4",   zh: "病毒性胃腸炎，未特定",             en: "Viral intestinal infection, unspecified", cat: "感染症" },
  { code: "A09",     zh: "感染性胃腸炎及結腸炎，未特定",       en: "Infectious gastroenteritis and colitis, unspecified", cat: "感染症" },
  { code: "A49.9",   zh: "細菌感染，未特定",                en: "Bacterial infection, unspecified", cat: "感染症" },
  { code: "B34.8",   zh: "其他病毒感染，未特定部位",         en: "Other viral infections of unspecified site", cat: "感染症" },
  { code: "B34.9",   zh: "病毒感染，未特定",                en: "Viral infection, unspecified", cat: "感染症" },
  { code: "B99.9",   zh: "傳染病，未特定",                  en: "Unspecified infectious disease", cat: "感染症" },
  { code: "B20",     zh: "HIV 疾病",                      en: "Human immunodeficiency virus disease", cat: "感染症", kw: "AIDS" },
  { code: "A41.9",   zh: "敗血症，未特定病原",              en: "Sepsis, unspecified organism", cat: "感染症" },
  { code: "A54.9",   zh: "淋病感染，未特定",                en: "Gonococcal infection, unspecified", cat: "感染症" },
  { code: "A60.9",   zh: "肛門生殖器皰疹病毒感染，未特定",    en: "Anogenital herpesviral infection, unspecified", cat: "感染症" },
  { code: "A63.0",   zh: "尖銳濕疣（肛門生殖器疣）",         en: "Anogenital (venereal) warts", cat: "感染症", kw: "HPV" },
  { code: "A53.9",   zh: "梅毒，未特定",                   en: "Syphilis, unspecified", cat: "感染症" },
  { code: "B19.20",  zh: "未特定病毒性C型肝炎，無肝昏迷",    en: "Unspecified viral hepatitis C without hepatic coma", cat: "感染症" },
  { code: "Z20.822", zh: "接觸並可能暴露於 COVID-19",       en: "Contact with and (suspected) exposure to COVID-19", cat: "感染症" },
  { code: "Z20.828", zh: "接觸並可能暴露於其他病毒",         en: "Contact with and (suspected) exposure to other viral communicable diseases", cat: "感染症" },

  // ========== 婦科/產科 ==========
  { code: "N92.6",   zh: "月經不規則，未特定",              en: "Irregular menstruation, unspecified", cat: "婦科/產科" },
  { code: "N91.2",   zh: "無月經，未特定",                  en: "Amenorrhea, unspecified", cat: "婦科/產科" },
  { code: "N94.6",   zh: "痛經，未特定",                   en: "Dysmenorrhea, unspecified", cat: "婦科/產科" },
  { code: "N94.3",   zh: "經前症候群",                     en: "Premenstrual tension syndrome", cat: "婦科/產科", kw: "PMS" },
  { code: "N95.1",   zh: "停經及圍停經期症狀",              en: "Menopausal and female climacteric states", cat: "婦科/產科" },
  { code: "N95.2",   zh: "停經後萎縮性陰道炎",              en: "Postmenopausal atrophic vaginitis", cat: "婦科/產科" },
  { code: "N76.0",   zh: "急性陰道炎",                     en: "Acute vaginitis", cat: "婦科/產科" },
  { code: "N76.1",   zh: "亞急性及慢性陰道炎",              en: "Subacute and chronic vaginitis", cat: "婦科/產科" },
  { code: "B37.3",   zh: "外陰及陰道念珠菌感染",            en: "Candidiasis of vulva and vagina", cat: "婦科/產科" },
  { code: "N72",     zh: "子宮頸炎",                      en: "Inflammatory disease of cervix uteri", cat: "婦科/產科" },
  { code: "N73.9",   zh: "骨盆腔炎性疾病，未特定",          en: "Female pelvic inflammatory disease, unspecified", cat: "婦科/產科", kw: "PID" },
  { code: "N80.9",   zh: "子宮內膜異位症，未特定",          en: "Endometriosis, unspecified", cat: "婦科/產科" },
  { code: "N83.209", zh: "卵巢囊腫，未特定，未特定側",       en: "Unspecified ovarian cyst, unspecified side", cat: "婦科/產科" },
  { code: "N85.9",   zh: "子宮非發炎性疾病，未特定",        en: "Noninflammatory disorder of uterus, unspecified", cat: "婦科/產科" },
  { code: "N92.0",   zh: "月經過多，週期規則",              en: "Excessive and frequent menstruation with regular cycle", cat: "婦科/產科" },
  { code: "N97.9",   zh: "女性不孕症，未特定",              en: "Female infertility, unspecified", cat: "婦科/產科" },
  { code: "Z30.011", zh: "初次處方口服避孕藥",              en: "Encounter for initial prescription of contraceptive pills", cat: "婦科/產科" },
  { code: "Z30.9",   zh: "避孕管理，未特定",                en: "Encounter for contraceptive management, unspecified", cat: "婦科/產科" },
  { code: "Z32.01",  zh: "懷孕檢測，結果陽性",              en: "Encounter for pregnancy test, result positive", cat: "婦科/產科" },
  { code: "Z32.02",  zh: "懷孕檢測，結果陰性",              en: "Encounter for pregnancy test, result negative", cat: "婦科/產科" },
  { code: "Z34.90",  zh: "正常懷孕監視，未特定三期",        en: "Encounter for supervision of normal pregnancy, unspecified, unspecified trimester", cat: "婦科/產科" },
  { code: "O26.90",  zh: "懷孕相關疾病，未特定",            en: "Pregnancy related conditions, unspecified, unspecified trimester", cat: "婦科/產科" },
  { code: "Z39.2",   zh: "產後例行追蹤",                   en: "Encounter for routine postpartum follow-up", cat: "婦科/產科" },
  { code: "N64.4",   zh: "乳房疼痛",                      en: "Mastodynia", cat: "婦科/產科" },
  { code: "N63.10",  zh: "右乳房未特定腫塊",                en: "Unspecified lump in the right breast, unspecified quadrant", cat: "婦科/產科" },
  { code: "R87.619", zh: "子宮頸抹片異常，未特定",           en: "Unspecified abnormal cytological findings in specimens from cervix uteri", cat: "婦科/產科" },

  // ========== 眼/耳鼻喉 ==========
  { code: "H10.9",   zh: "結膜炎，未特定",                  en: "Unspecified conjunctivitis", cat: "眼/耳鼻喉" },
  { code: "H10.10",  zh: "急性過敏性結膜炎，未特定眼",       en: "Acute atopic conjunctivitis, unspecified eye", cat: "眼/耳鼻喉" },
  { code: "H10.30",  zh: "急性結膜炎，未特定，未特定眼",     en: "Unspecified acute conjunctivitis, unspecified eye", cat: "眼/耳鼻喉" },
  { code: "H16.9",   zh: "角膜炎，未特定",                  en: "Unspecified keratitis", cat: "眼/耳鼻喉" },
  { code: "H00.019", zh: "麥粒腫（針眼），未特定眼瞼",        en: "Hordeolum externum unspecified eye, unspecified eyelid", cat: "眼/耳鼻喉" },
  { code: "H00.0",   zh: "麥粒腫及眼瞼其他深部發炎",          en: "Hordeolum and other deep inflammation of eyelid", cat: "眼/耳鼻喉" },
  { code: "H01.009", zh: "眼瞼炎，未特定",                  en: "Unspecified blepharitis unspecified eye, unspecified eyelid", cat: "眼/耳鼻喉" },
  { code: "H04.9",   zh: "淚器疾病，未特定",                en: "Disorder of lacrimal system, unspecified", cat: "眼/耳鼻喉" },
  { code: "H11.30",  zh: "結膜出血，未特定眼",              en: "Conjunctival hemorrhage, unspecified eye", cat: "眼/耳鼻喉" },
  { code: "H25.9",   zh: "老年性白內障，未特定",             en: "Unspecified age-related cataract", cat: "眼/耳鼻喉" },
  { code: "H40.9",   zh: "青光眼，未特定",                 en: "Unspecified glaucoma", cat: "眼/耳鼻喉" },
  { code: "H52.13",  zh: "雙眼近視",                       en: "Myopia, bilateral", cat: "眼/耳鼻喉" },
  { code: "H52.4",   zh: "老花眼",                        en: "Presbyopia", cat: "眼/耳鼻喉" },
  { code: "H53.9",   zh: "視覺障礙，未特定",                en: "Unspecified visual disturbance", cat: "眼/耳鼻喉" },
  { code: "H57.10",  zh: "眼痛，未特定眼",                 en: "Ocular pain, unspecified eye", cat: "眼/耳鼻喉" },
  { code: "H60.90",  zh: "外耳炎，未特定，未特定耳",         en: "Unspecified otitis externa, unspecified ear", cat: "眼/耳鼻喉" },
  { code: "H66.90",  zh: "中耳炎，未特定，未特定耳",         en: "Otitis media, unspecified, unspecified ear", cat: "眼/耳鼻喉" },
  { code: "H65.90",  zh: "非化膿性中耳炎，未特定，未特定耳",   en: "Unspecified nonsuppurative otitis media, unspecified ear", cat: "眼/耳鼻喉" },
  { code: "H61.20",  zh: "耳垢阻塞，未特定耳",              en: "Impacted cerumen, unspecified ear", cat: "眼/耳鼻喉" },
  { code: "H91.90",  zh: "聽力喪失，未特定，未特定耳",       en: "Unspecified hearing loss, unspecified ear", cat: "眼/耳鼻喉" },
  { code: "H93.19",  zh: "耳鳴，未特定耳",                  en: "Tinnitus, unspecified ear", cat: "眼/耳鼻喉" },
  { code: "R04.0",   zh: "流鼻血",                        en: "Epistaxis", cat: "眼/耳鼻喉" },
  { code: "J34.3",   zh: "鼻中膈肥厚",                     en: "Hypertrophy of nasal turbinates", cat: "眼/耳鼻喉" },

  // ========== 外傷/意外 ==========
  { code: "S00.83XA", zh: "其他部位頭部擦傷，初診",           en: "Abrasion of other part of head, initial encounter", cat: "外傷/意外" },
  { code: "S01.81XA", zh: "其他部位頭部開放性傷口，初診",      en: "Laceration without foreign body of other part of head, initial encounter", cat: "外傷/意外" },
  { code: "S06.0X0A", zh: "腦震盪，無意識喪失，初診",         en: "Concussion without loss of consciousness, initial encounter", cat: "外傷/意外" },
  { code: "S09.90XA", zh: "頭部外傷，未特定，初診",           en: "Unspecified injury of head, initial encounter", cat: "外傷/意外" },
  { code: "S93.401A", zh: "右踝關節扭傷，初診",              en: "Sprain of unspecified ligament of right ankle, initial encounter", cat: "外傷/意外" },
  { code: "S93.402A", zh: "左踝關節扭傷，初診",              en: "Sprain of unspecified ligament of left ankle, initial encounter", cat: "外傷/意外" },
  { code: "S83.501A", zh: "右膝十字韌帶扭傷，初診",          en: "Sprain of unspecified cruciate ligament of right knee, initial encounter", cat: "外傷/意外" },
  { code: "S39.012A", zh: "腹部、下背部及骨盆肌肉拉傷，初診",   en: "Strain of muscle, fascia and tendon of lower back, initial encounter", cat: "外傷/意外" },
  { code: "T14.90",  zh: "受傷，未特定",                   en: "Injury, unspecified", cat: "外傷/意外" },
  { code: "W19.XXXA", zh: "跌倒，未特定，初診",              en: "Unspecified fall, initial encounter", cat: "外傷/意外" },
  { code: "S72.009A", zh: "股骨頸閉鎖性骨折，未特定側，初診",   en: "Fracture of unspecified part of neck of unspecified femur, initial encounter for closed fracture", cat: "外傷/意外" },
  { code: "S62.609A", zh: "手指閉鎖性骨折，未特定，初診",     en: "Fracture of unspecified phalanx of unspecified finger, initial encounter for closed fracture", cat: "外傷/意外" },
  { code: "S52.501A", zh: "右橈骨下端閉鎖性骨折，初診",      en: "Unspecified fracture of the lower end of right radius, initial encounter for closed fracture", cat: "外傷/意外" },
  { code: "T78.40XA", zh: "過敏反應，未特定，初診",          en: "Allergy, unspecified, initial encounter", cat: "外傷/意外" },
  { code: "T88.7XXA", zh: "藥物或藥品之不良反應，初診",      en: "Unspecified adverse effect of drug or medicament, initial encounter", cat: "外傷/意外" },

  // ========== 其他常見 ==========
  { code: "D50.9",   zh: "缺鐵性貧血，未特定",              en: "Iron deficiency anemia, unspecified", cat: "其他" },
  { code: "D64.9",   zh: "貧血，未特定",                    en: "Anemia, unspecified", cat: "其他" },
  { code: "D51.0",   zh: "惡性貧血（維生素B12吸收不良）",     en: "Vitamin B12 deficiency anemia due to intrinsic factor deficiency", cat: "其他" },
  { code: "D52.9",   zh: "葉酸缺乏性貧血，未特定",           en: "Folate deficiency anemia, unspecified", cat: "其他" },
  { code: "D53.9",   zh: "營養性貧血，未特定",              en: "Nutritional anemia, unspecified", cat: "其他" },
  { code: "D72.829", zh: "白血球增多，未特定",              en: "Elevated white blood cell count, unspecified", cat: "其他" },
  { code: "D69.6",   zh: "血小板減少，未特定",              en: "Thrombocytopenia, unspecified", cat: "其他" },
  { code: "R79.89",  zh: "其他特定之血液化學檢查異常",        en: "Other specified abnormal findings of blood chemistry", cat: "其他" },
  { code: "R79.9",   zh: "血液化學檢查異常，未特定",         en: "Abnormal finding of blood chemistry, unspecified", cat: "其他" },
  { code: "R94.30",  zh: "心血管功能檢查異常，未特定",        en: "Abnormal result of cardiovascular function study, unspecified", cat: "其他" },
  { code: "R93.5",   zh: "腹部影像檢查異常",                en: "Abnormal findings on diagnostic imaging of other abdominal regions", cat: "其他" },
  { code: "R91.8",   zh: "其他肺部影像異常",                en: "Other nonspecific abnormal finding of lung field", cat: "其他" },
];

// 類別順序（顯示用）
const CATEGORY_ORDER = [
  "糖尿病", "高血壓", "高血脂", "心血管",
  "呼吸系統", "腎臟泌尿", "內分泌代謝", "骨骼肌肉",
  "精神/睡眠", "消化系統", "神經系統", "眼/耳鼻喉",
  "皮膚", "婦科/產科", "感染症", "外傷/意外",
  "健檢/預防", "常見症狀", "其他",
];
